/**
 * AUTO-GENERATED by scripts/sync-addresses.js
 * DO NOT EDIT MANUALLY.
 * Last deployed: 2026-08-15T15:23:16.170Z on localhost (Chain ID: 31337)
 */

export const DEPLOYED_ADDRESSES = {
  "AltanaSessionManager": "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
  "SyrupSentinelAgent": "0x0165878A594ca255338adfa4d48449f69242Eb8F",
  "VenusGuardianAgent": "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
  "YieldMaxAgent": "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
  "ChainWatchAgent": "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318",
  "PancakeV3Router": "0x1B81D678fFB0c8B614eb42968695Da4E8c5A8c93",
  "PancakeV2Router": "0xD99D1c33F9fC3444f8101754aBC46c52416550D1"
};

export const DEPLOYMENT_META = {
  network: "localhost",
  chainId: 31337,
  deployedAt: "2026-08-15T15:23:16.170Z",
};
